# Generated by Django 5.0.7 on 2024-07-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('for_contest', models.BooleanField(default=False)),
                ('has_image', models.BooleanField(default=False)),
            ],
        ),
    ]
