# Generated by Django 5.0.7 on 2024-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_coderunner_alter_problem_difficulty_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='coderunner',
            name='language',
            field=models.CharField(blank=True, choices=[('py', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C')], max_length=10),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(max_length=255),
        ),
    ]
