# Generated by Django 5.0.7 on 2024-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_coderunner_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
